default:
    @just --list

[private]
install pkgs:
    yay -S --needed {{ pkgs }}

# fonts:
#     just install """
#     noto-fonts
#     noto-fonts-emoji
#     ttf-jetbrains-mono
#     adwaita-fonts
#     inter-font
#     """
